### ISSUE TITLE
Current offline [Feature Request]

### ISSUE THREAD

**Issue by notelho** [kittinan/spotify-github-profile#24]
# Overview
Hi! First of all, great work on this plugin!

I want to request a current offline template when nothing are being played. I made a simple template draft ([screenshot one](#offline-template-draft), also attached in the issue). Currently, I don't know if there is a url param to not throw an error if an advertising is playing, but actually, the server is throwing this error in my response ([screenshot two](#error-while-advertising)).

> Note that related error happens every time that an advertising is playing on my account.

# Screenshots

## Offline template draft

![image](https://user-images.githubusercontent.com/39466625/129467267-0a6ad6c4-dc47-4f80-a94b-139be3aa9919.png)

## Error while advertising

![image](https://user-images.githubusercontent.com/39466625/129467662-fa51540e-81a9-46ce-be29-17f1a9a1f2a2.png)
![image](https://user-images.githubusercontent.com/39466625/129467402-5122446d-fd46-4166-a4cd-85e40e4b713c.png)

# Files

## Offline template svg

[offline.zip](https://github.com/kittinan/spotify-github-profile/files/6987523/offline.zip)

**Comment by deepansharya1111** [comment]
This is such a great idea!

**Comment by LucasMZReal** [comment]
I would really love this.
For me, having it so that it just chooses random songs when you're not playing defeats the purpose of having it in the first place.
You wanna show off the songs you're listening to, and if you're not listening to something, and it says you are, you're not doing that anymore. Someone looking at it can't tell if you're actually listening to something. (apart from refreshing and seeing if songs always change, which usually means the user is offline, but you have to USE this and know that, which most people just won't)

I can see a place for having an option where you can select it on the website, but really not having the option of just it saying "Nothing playing right now!" or similar, defeats the purpose completely for me.

**Comment by kittinan** [comment]
done

**Comment by ReWelp** [comment]
Yo it doesnt work it still shows I'm playing the song I'm playing
![image](https://user-images.githubusercontent.com/109627279/194788705-0b4699a0-1e94-4ec7-828c-8f2a662e966d.png)
